### ISSUE TITLE
Add new habit form validation

### ISSUE THREAD

**Issue by vitorwlima** [vitorwlima/habit-tracker#17]
Needs to have at least 1 day tagged, and habit name should exist (at least 1 char or 3)

- use zod probably

**Comment by alexisveryreal** [comment]
May i take this? We can probably use react-hook-form + zod, and do something like [useZodForm from trpc kitchen sink](https://kitchen-sink.trpc.io/react-hook-form?file=feature%2Freact-hook-form%2Findex.tsx#content)

**Comment by vitorwlima** [comment]
absolutely, go for it man!

I'm doing the form by hand for now, without any external libs, so it's up to you if you want to add react-hook-form to make it work or pure zod.
